Prices:
  Air: 0
  Dirt: 3
  Cobblestone: 4
  Wood: 5
  Sapling: 6
  Bedrock: 7
  Water: 8
  StationaryWater: 9
  Lava: 10
  StationaryLava: 11
  Sand: 12
  Gravel: 13
  GoldOre: 14
  IronOre: 15
  CoalOre: 16
  Log: 17
  Leaves: 18
  Sponge: 19
  Glass: 20
  LapisOre: 21
  LapisBlock: 22
  Dispenser: 23
  Sandstone: 24
  NoteBlock: 25
  BedBlock: 26
  PoweredRail: 27
  DetectorRail: 28
  PistonStickyBase: 29
  Web: 30
  LongGrass: 31
  DeadBush: 32
  PistonBase: 33
  PistonExtension: 34
  Wool: 35
  PistonMovingPiece: 36
  YellowFlower: 37
  RedRose: 38
  BrownMushroom: 39
  RedMushroom: 40
  GoldBlock: 41
  IronBlock: 42
  DoubleStep: 43
  Step: 44
  Brick: 45
  Tnt: 46
  Bookshelf: 47
  MossyCobblestone: 48
  Obsidian: 49
  Torch: 50
  Fire: 51
  MobSpawner: 52
  WoodStairs: 53
  Chest: 54
  RedstoneWire: 55
  DiamondOre: 56
  DiamondBlock: 57
  Workbench: 58
  Crops: 59
  Soil: 60
  Furnace: 61
  BurningFurnace: 62
  SignPost: 63
  WoodenDoor: 64
  Ladder: 65
  Rails: 66
  CobblestoneStairs: 67
  WallSign: 68
  Lever: 69
  StonePlate: 70
  IronDoorBlock: 71
  WoodPlate: 72
  RedstoneOre: 73
  GlowingRedstoneOre: 74
  RedstoneTorchOff: 75
  RedstoneTorchOn: 76
  StoneButton: 77
  Snow: 78
  Ice: 79
  SnowBlock: 80
  Cactus: 81
  Clay: 82
  SugarCaneBlock: 83
  Jukebox: 84
  Fence: 85
  Pumpkin: 86
  Netherrack: 87
  SoulSand: 88
  Glowstone: 89
  Portal: 90
  JackOLantern: 91
  CakeBlock: 92
  DiodeBlockOff: 93
  DiodeBlockOn: 94
  LockedChest: 95
  TrapDoor: 96
  MonsterEggs: 97
  SmoothBrick: 98
  HugeMushroom1: 99
  HugeMushroom2: 100
  IronFence: 101
  ThinGlass: 102
  MelonBlock: 103
  PumpkinStem: 104
  MelonStem: 105
  Vine: 106
  FenceGate: 107
  BrickStairs: 108
  SmoothStairs: 109
  Mycel: 110
  WaterLily: 111
  NetherBrick: 112
  NetherFence: 113
  NetherBrickStairs: 114
  NetherWarts: 115
  EnchantmentTable: 116
  BrewingStand: 117
  Cauldron: 118
  EnderPortal: 119
  EnderPortalFrame: 120
  EnderStone: 121
  DragonEgg: 122
  RedstoneLampOff: 123
  RedstoneLampOn: 124
  WoodDoubleStep: 125
  WoodStep: 126
  Cocoa: 127
  SandstoneStairs: 128
  EmeraldOre: 129
  EnderChest: 130
  TripwireHook: 131
  Tripwire: 132
  EmeraldBlock: 133
  SpruceWoodStairs: 134
  BirchWoodStairs: 135
  JungleWoodStairs: 136
  Command: 137
  Beacon: 138
  CobbleWall: 139
  FlowerPot: 140
  Carrot: 141
  Potato: 142
  WoodButton: 143
  Skull: 144
  Anvil: 145
  IronSpade: 256
  IronPickaxe: 257
  IronAxe: 258
  FlintAndSteel: 259
  Apple: 260
  Bow: 261
  Arrow: 262
  Coal: 263
  Diamond: 264
  IronIngot: 265
  GoldIngot: 266
  IronSword: 267
  WoodSword: 268
  WoodSpade: 269
  WoodPickaxe: 270
  WoodAxe: 271
  StoneSword: 272
  StoneSpade: 273
  StonePickaxe: 274
  StoneAxe: 275
  DiamondSword: 276
  DiamondSpade: 277
  DiamondPickaxe: 278
  DiamondAxe: 279
  Stick: 280
  Bowl: 281
  MushroomSoup: 282
  GoldSword: 283
  GoldSpade: 284
  GoldPickaxe: 285
  GoldAxe: 286
  String: 287
  Feather: 288
  Sulphur: 289
  WoodHoe: 290
  StoneHoe: 291
  IronHoe: 292
  DiamondHoe: 293
  GoldHoe: 294
  Seeds: 295
  Wheat: 296
  Bread: 297
  LeatherHelmet: 298
  LeatherChestplate: 299
  LeatherLeggings: 300
  LeatherBoots: 301
  ChainmailHelmet: 302
  ChainmailChestplate: 303
  ChainmailLeggings: 304
  ChainmailBoots: 305
  IronHelmet: 306
  IronChestplate: 307
  IronLeggings: 308
  IronBoots: 309
  DiamondHelmet: 310
  DiamondChestplate: 311
  DiamondLeggings: 312
  DiamondBoots: 313
  GoldHelmet: 314
  GoldChestplate: 315
  GoldLeggings: 316
  GoldBoots: 317
  Flint: 318
  Pork: 319
  GrilledPork: 320
  Painting: 321
  GoldenApple: 322
  Sign: 323
  WoodDoor: 324
  Bucket: 325
  WaterBucket: 326
  LavaBucket: 327
  Minecart: 328
  Saddle: 329
  IronDoor: 330
  Redstone: 331
  SnowBall: 332
  Boat: 333
  Leather: 334
  MilkBucket: 335
  ClayBrick: 336
  ClayBall: 337
  SugarCane: 338
  Paper: 339
  Book: 340
  SlimeBall: 341
  StorageMinecart: 342
  PoweredMinecart: 343
  Egg: 344
  Compass: 345
  FishingRod: 346
  Watch: 347
  GlowstoneDust: 348
  RawFish: 349
  CookedFish: 350
  InkSack: 351
  Bone: 352
  Sugar: 353
  Cake: 354
  Bed: 355
  Diode: 356
  Cookie: 357
  Map: 358
  Shears: 359
  Melon: 360
  PumpkinSeeds: 361
  MelonSeeds: 362
  RawBeef: 363
  CookedBeef: 364
  RawChicken: 365
  CookedChicken: 366
  RottenFlesh: 367
  EnderPearl: 368
  BlazeRod: 369
  GhastTear: 370
  GoldNugget: 371
  NetherStalk: 372
  Potion: 373
  GlassBottle: 374
  SpiderEye: 375
  FermentedSpiderEye: 376
  BlazePowder: 377
  MagmaCream: 378
  BrewingStandItem: 379
  CauldronItem: 380
  EyeOfEnder: 381
  SpeckledMelon: 382
  MonsterEgg: 383
  ExpBottle: 384
  Fireball: 385
  BookAndQuill: 386
  WrittenBook: 387
  Emerald: 388
  ItemFrame: 389
  FlowerPotItem: 390
  CarrotItem: 391
  PotatoItem: 392
  BakedPotato: 393
  PoisonousPotato: 394
  EmptyMap: 395
  GoldenCarrot: 396
  SkullItem: 397
  CarrotStick: 398
  NetherStar: 399
  PumpkinPie: 400
  GoldRecord: 2256
  GreenRecord: 2257
  Record3: 2258
  Record4: 2259
  Record5: 2260
  Record6: 2261
  Record7: 2262
  Record8: 2263
  Record9: 2264
  Record10: 2265
  Record11: 2266